### ISSUE TITLE
Scrollbar Position Issue when div is display:none;

### ISSUE THREAD

**Issue by solverat** [julianlam/Scrollable#6]
Hey,

if the scroll-div is invisible or hidden in its parent, the scrollbar position will be wrong. (as long as you do the first move event).

mootools cant get the "getPosition" while the element is not visible. i changed the function "reposition"  like this: 

``` javascript
if(this.element.isVisible())
    this.position = this.element.getPosition();
else
    this.position = this.element.measure(function(){
         return this.getSize(); });
```

**Comment by julianlam** [comment]
Hm. This sounds similar to an issue I fixed recently. Which version of the plugin are you using?

In hindsight, I don't actually publish the version number anywhere in the code except in the package.yml file, which really doesn't help...

At any rate, I believe I fixed it already by using `Element.measure`, as you have also done, and pushed the new version out to the plugins page. Can you reproduce it on [this fiddle](http://jsfiddle.net/Wk8YP/23/)?

**Comment by solverat** [comment]
Hey, 

i reprduced it on jsfiddle:

http://jsfiddle.net/Wk8YP/51/

the problem is still alive.
- click the "show" button. 
- scroll over the container. the scrollbar will fade in on a wrong calculated position.

**Comment by julianlam** [comment]
Odd, there seems to be an issue where "this" in `reposition();` keeps referring to the container, instead of the target element. I'm going to attribute this to a case of the Mondays, and tackle this later.

Thanks for bringing this to my attention!

(By the way, any particular reason why you're running `getSize();` in the else clause of your fix instead of `getPosition();`? ;)

**Comment by julianlam** [comment]
Zwacky just coded a possible fix to this - can you verify that the this bug is still reproducible in the latest git version?

https://github.com/julianlam/Scrollable/pull/8

**Comment by zwacky** [comment]
yes, it fixed this issue
http://jsfiddle.net/Wk8YP/85/

**Comment by julianlam** [comment]
Fantastic, thanks.
